### ISSUE TITLE
Need some help with linearization

### ISSUE THREAD

**Issue by wyhsoochow** [SapienzaNLP/gsrl#1]
Thank you very much for your contribution in gsrl!
Your design for **NESTED SPAN-BASED SRL**  really inspired me , but I have trouble with how to merge some SRL sentences into one NESTED sentence ,  I would be very grateful if you could make this preprocessing method for this part in public .

**Comment by rexhinab** [comment]
Hello! 
Thank you for your interest in our work. Actually, the linearizations are computed on the fly when you disable the duplicate-per-predicate flag ([in this method](https://github.com/SapienzaNLP/gsrl/blob/64291a79c79c212cc5fb025cf5fa33de74445e44/src/modelling/tokenization_bart.py#L214)). Let us know if this helps you! 

Cheers
